all:
	g++ speex_decode.cpp speex_encode.cpp  AmMultiPartyMixer.cpp  mix_pcm.cpp -I/home/chris/work/audio_process/mix_pcm/output/include -L/home/chris/work/audio_process/mix_pcm/output/lib -lspeex -lm
